name: CI

on:
push:
pull_request:

jobs:
build-and-test:
runs-on: ubuntu-24.04
steps:
- uses: actions/checkout@v4

-name: Setup ROS 2 Jazzy
uses: ros-tooling/setup-ros@v0.7
with:
required-ros-distributions: jazzy

-name: Install dependencies
run: |
sudo apt update
rosdep update
cd ros_ws
rosdep install --from-paths src --ignore-src -r -y

-name: Build
run: |
source /opt/ros/jazzy/setup.bash
cd ros_ws
colcon test --event-handlers console_direct+
colcon test-result --verbose
